language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"
node_js:
- '8'
- '10'
deploy:
  provider: npm
  email: hatatatehaze@gmail.com
  api_key:
    secure: PBwMJ/PNF5eBGrdyiPNOMn+6nnTP+/k6qVNLa3oeLfLTZQJP33JShw2XdH41TTCG2hTL+w2ZWlJaoVaSpiwRqamPkhrAiLAQxfcY9w9E6xwOA3bGXRGyy+Iv7YZSYMcwPFl+4+l2flrBYHT0DzHYz71vVTen3xSBBVW/OIKvLkAb+di+IRZJfbpmrUkL5Cft2idYjsnE8giQHxYbpwPe5kd0qnBpyxv4yE7EH1ueF5a5t5kddWQuW/rX6Ma4ZTp/C5WTTp9pS1iyUm4z1iKH4rQhPc/sByCEaa+S+4Ubw3dRPMWA8dYWUOcG1VT6rp76dEr4R5S8MpdahDVoqLB3n3nmSLo0A4wC7zBWlxAP3lQ3ofnaDhl1zyI9X6tCD7jc6u5QwLoP8lCbKaPBsI6GZBXujQ9mnSOXpVBXxP6/ZJW+DdR4YEm79fc7v6ktb/eAD9P3OUxQNm/QY+KTPILDC5fbR4Lk51AlLrqbJubJOS0H5SEUSl8iIi5PKqKYLo3Qg01zyed3c/oJVA3QBHHI0btH/DPCtlFl4Q5U1J6YdcnrVCPI1WsXoVhGwNO7/OsPKG1sF5AOZ5KPeE4pPUFbh/jKFzHQLrifilNIgv0hNswb/LYbSw0kXjSsXUX/r76CqIrxaJGt9tvAq7A8kjv0WwUyxYpVYuObMhBFEPV0fy8=
  on:
    branch: master
    tags: true
    repo: tilecloud/mbgl-fork-me-control
  skip_cleanup: true
